name: "Lint All The Things"
description: "Composite action to run various linters (see README) on a codebase, auto-committing and pushing changes if needed."
author: "Cline"
inputs:
  python-version:
    description: "Python version to use (eg. 3.9 3.10)"
  pyupgrade-target-version:
    description: "Python version to target for pyupgrade (eg. py39 py310)"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Initialize changed linters list
      shell: bash
      run: |
        echo "changed_linters=" >> "$GITHUB_ENV"
        echo "changed_linter_labels=" >> "$GITHUB_ENV"

    - name: Install PyUpgrade
      shell: bash
      run: pip install pyupgrade

    - name: Run PyUpgrade
      shell: bash
      run: |
        before_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)
        find . -name '*.py' -exec pyupgrade --${{ inputs.pyupgrade-target-version }}-plus --exit-zero-even-if-changed {} +
        after_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}pyupgrade" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }pyupgrade --${{ inputs.pyupgrade-target-version }}-plus" >> "$GITHUB_ENV"
        fi

    - name: Install isort
      shell: bash
      run: pip install isort

    - name: Run isort
      shell: bash
      run: |
        before_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)
        isort .
        after_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}isort" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }isort" >> "$GITHUB_ENV"
        fi

    - name: Install Black
      shell: bash
      run: pip install black

    - name: Run Black
      shell: bash
      run: |
        before_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)
        black .
        after_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}black" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }black ." >> "$GITHUB_ENV"
        fi

    - name: Install Autoflake
      shell: bash
      run: pip install autoflake

    - name: Run Autoflake
      shell: bash
      run: |
        before_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)
        autoflake --remove-all-unused-imports --in-place --expand-star-imports --ignore-init-module-imports -r .
        after_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}autoflake" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }autoflake --remove-all-unused-imports --in-place --expand-star-imports --ignore-init-module-imports -r ." >> "$GITHUB_ENV"
        fi

    - name: Check for JSON files
      id: json_files
      shell: bash
      run: |
        if git ls-files -- '*.json' | grep -q .; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Run Prettier (JSON)
      if: steps.json_files.outputs.found == 'true'
      shell: bash
      run: |
        before_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)
        if [[ -x ./node_modules/.bin/prettier ]]; then
          git ls-files -z -- '*.json' | xargs -0 -r ./node_modules/.bin/prettier --write
        else
          git ls-files -z -- '*.json' | xargs -0 -r npx --yes prettier --write
        fi
        after_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          if [[ ",$changed_linters," != *",prettier,"* ]]; then
            echo "changed_linters=${changed_linters:+$changed_linters,}prettier" >> "$GITHUB_ENV"
          fi
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }prettier --write *.json" >> "$GITHUB_ENV"
        fi

    - name: Check for YAML files
      id: yaml_files
      shell: bash
      run: |
        if git ls-files -- '*.yml' '*.yaml' | grep -q .; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Run Prettier (YAML)
      if: steps.yaml_files.outputs.found == 'true'
      shell: bash
      run: |
        before_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)
        if [[ -x ./node_modules/.bin/prettier ]]; then
          git ls-files -z -- '*.yml' '*.yaml' | xargs -0 -r ./node_modules/.bin/prettier --write
        else
          git ls-files -z -- '*.yml' '*.yaml' | xargs -0 -r npx --yes prettier --write
        fi
        after_hash=$(git diff --no-color | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          if [[ ",$changed_linters," != *",prettier,"* ]]; then
            echo "changed_linters=${changed_linters:+$changed_linters,}prettier" >> "$GITHUB_ENV"
          fi
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }prettier --write *.yml *.yaml" >> "$GITHUB_ENV"
        fi

    - name: Commit changes (all linters)
      if: env.changed_linters != ''
      uses: BobTheBuidler/poosh@v0.0.8
      with:
        commit-message: "chore: lint (${{ env.changed_linter_labels || env.changed_linters }})"
        trigger-branch: ${{ github.head_ref || github.ref_name }}
        trigger-pr-number: ${{ github.event.pull_request.number }}
        pr-base: ${{ github.event.pull_request && github.event.pull_request.head.repo.full_name != github.repository && github.base_ref || '' }}
