name: "Lint All The Things"
description: "Composite action to run various linters (see README) on a codebase, auto-committing and pushing changes if needed."
author: "Cline"
inputs:
  python-version:
    description: "Python version to use (eg. 3.9 or 3.10)"
  pyupgrade-target-version:
    description: "Python version to target for pyupgrade (eg. py39 or py310)"
runs:
  using: "composite"
  steps:
    - name: Stage linter requirements for cache key
      shell: bash
      run: cp "${{ github.action_path }}/requirements-python.txt" .lint-all-the-things-requirements.txt

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"
        cache-dependency-path: .lint-all-the-things-requirements.txt

    - name: Initialize changed linters list
      shell: bash
      run: |
        echo "changed_linters=" >> "$GITHUB_ENV"
        echo "changed_linter_labels=" >> "$GITHUB_ENV"

    - name: Install Python linters
      shell: bash
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: "1" # Skip the self-update check to reduce noise/network.
        PIP_NO_PYTHON_VERSION_WARNING: "1" # Suppress Python version warnings; no effect on installs.
      run: python -m pip install -r .lint-all-the-things-requirements.txt

    - name: Clean up linter requirements
      shell: bash
      run: rm -f .lint-all-the-things-requirements.txt

    - name: Run PyUpgrade
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        find . -name '*.py' -exec pyupgrade --${{ inputs.pyupgrade-target-version }}-plus --exit-zero-even-if-changed {} +
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}pyupgrade" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }pyupgrade --${{ inputs.pyupgrade-target-version }}-plus" >> "$GITHUB_ENV"
        fi

    - name: Run isort
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        isort .
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}isort" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }isort" >> "$GITHUB_ENV"
        fi

    - name: Run Black
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        black .
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}black" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }black ." >> "$GITHUB_ENV"
        fi

    - name: Run Autoflake
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        autoflake --remove-all-unused-imports --in-place --expand-star-imports --ignore-init-module-imports -r .
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}autoflake" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }autoflake --remove-all-unused-imports --in-place --expand-star-imports --ignore-init-module-imports -r ." >> "$GITHUB_ENV"
        fi

    - name: Collect JSON files
      id: json_files
      shell: bash
      run: |
        json_file_list="$RUNNER_TEMP/lint-all-the-things-json-files" # Save list for reuse in Prettier run.
        git ls-files -z -- '*.json' > "$json_file_list"
        if [[ -s "$json_file_list" ]]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi
        echo "list=$json_file_list" >> "$GITHUB_OUTPUT"

    - name: Run Prettier (JSON)
      if: steps.json_files.outputs.found == 'true'
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        if [[ -x ./node_modules/.bin/prettier ]]; then
          xargs -0 -r -a "${{ steps.json_files.outputs.list }}" ./node_modules/.bin/prettier --write
        else
          xargs -0 -r -a "${{ steps.json_files.outputs.list }}" npx --yes prettier@3.8.0 --write # Pin fallback Prettier for reproducible output.
        fi
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          if [[ ",$changed_linters," != *",prettier,"* ]]; then
            echo "changed_linters=${changed_linters:+$changed_linters,}prettier" >> "$GITHUB_ENV"
          fi
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }prettier --write *.json" >> "$GITHUB_ENV"
        fi

    - name: Collect YAML files
      id: yaml_files
      shell: bash
      run: |
        yaml_file_list="$RUNNER_TEMP/lint-all-the-things-yaml-files" # Save list for reuse in Prettier run.
        git ls-files -z -- '*.yml' '*.yaml' > "$yaml_file_list"
        if [[ -s "$yaml_file_list" ]]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi
        echo "list=$yaml_file_list" >> "$GITHUB_OUTPUT"

    - name: Run Prettier (YAML)
      if: steps.yaml_files.outputs.found == 'true'
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        if [[ -x ./node_modules/.bin/prettier ]]; then
          xargs -0 -r -a "${{ steps.yaml_files.outputs.list }}" ./node_modules/.bin/prettier --write
        else
          xargs -0 -r -a "${{ steps.yaml_files.outputs.list }}" npx --yes prettier@3.8.0 --write # Pin fallback Prettier for reproducible output.
        fi
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          if [[ ",$changed_linters," != *",prettier,"* ]]; then
            echo "changed_linters=${changed_linters:+$changed_linters,}prettier" >> "$GITHUB_ENV"
          fi
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }prettier --write *.yml *.yaml" >> "$GITHUB_ENV"
        fi

    - name: Collect Markdown files
      id: markdown_files
      shell: bash
      run: |
        markdown_file_list="$RUNNER_TEMP/lint-all-the-things-markdown-files"
        git ls-files -z -- '*.md' > "$markdown_file_list"
        if [[ -s "$markdown_file_list" ]]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi
        echo "list=$markdown_file_list" >> "$GITHUB_OUTPUT"

    - name: Run markdownlint-cli2 (Markdown)
      if: steps.markdown_files.outputs.found == 'true'
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        if [[ -x ./node_modules/.bin/markdownlint-cli2 ]]; then
          xargs -0 -r -a "${{ steps.markdown_files.outputs.list }}" ./node_modules/.bin/markdownlint-cli2 --no-globs --fix
        else
          xargs -0 -r -a "${{ steps.markdown_files.outputs.list }}" npx --yes markdownlint-cli2@0.21.0 --no-globs --fix
        fi
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}markdownlint-cli2" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }markdownlint-cli2 --fix *.md" >> "$GITHUB_ENV"
        fi

    - name: Collect TOML files
      id: toml_files
      shell: bash
      run: |
        toml_file_list="$RUNNER_TEMP/lint-all-the-things-toml-files"
        git ls-files -z -- '*.toml' > "$toml_file_list"
        if [[ -s "$toml_file_list" ]]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi
        echo "list=$toml_file_list" >> "$GITHUB_OUTPUT"

    - name: Run Taplo (TOML)
      if: steps.toml_files.outputs.found == 'true'
      shell: bash
      run: |
        before_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1) # Zero-context diff keeps hash input smaller.
        if [[ -x ./node_modules/.bin/taplo ]]; then
          xargs -0 -r -a "${{ steps.toml_files.outputs.list }}" ./node_modules/.bin/taplo format
        else
          xargs -0 -r -a "${{ steps.toml_files.outputs.list }}" npx --yes @taplo/cli@0.7.0 format
        fi
        after_hash=$(git diff --no-color --unified=0 | sha256sum | cut -d' ' -f1)

        if [[ "$before_hash" != "$after_hash" ]]; then
          echo "changed_linters=${changed_linters:+$changed_linters,}taplo" >> "$GITHUB_ENV"
          echo "changed_linter_labels=${changed_linter_labels:+$changed_linter_labels; }taplo format *.toml" >> "$GITHUB_ENV"
        fi

    - name: Commit changes (all linters)
      if: env.changed_linters != ''
      uses: BobTheBuidler/poosh@v0.0.12
      with:
        commit-message: "chore: lint (${{ env.changed_linter_labels || env.changed_linters }})"
        trigger-branch: ${{ github.head_ref || github.ref_name }}
        trigger-pr-number: ${{ github.event.pull_request.number }}
        pr-base: ${{ github.event.pull_request && github.event.pull_request.head.repo.full_name != github.repository && github.base_ref || '' }}
